### ISSUE TITLE
task 153

### ISSUE THREAD

**Issue by PashaKycher** [AgileNix/coderslang-feedback#73]
## Test result 

  - [x] isKeyPresent should be exported from the file helper.js
        
  - [x] getObjectKeys should be a function
        
  - [ ] The function getObjectKeys test if the object has certain key
        
#### task153/helper.js
  ```js
  export const isKeyPresent = (obj, key) => {
  let objKey = Object.keys(obj);
    for (let i=0; i<objKey.length; i++){
      if (objKey[i] === key){
        return key;
      }
    }

}
  ```
        
  #### task153/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task153/solution.js
  ```js
  /**
 * Implement the function isKeyPresent which checks if the object has a certain field
 * */

import { isKeyPresent } from './helper.js';

const user = {
  name: 'Tom',
  age: '2',
  isHappy: true,
  createdAt: '2020-01-01'
}

console.log(isKeyPresent(user, 'name'));
console.log(isKeyPresent(user, 'address'));


  ```

**Comment by ssfxate** [comment]
What are you returning in the function isKeyPresent()? Why do you returning this?

**Comment by PashaKycher** [comment]
let objKey = Object.keys(obj);
    for (let i=0; i<objKey.length; i++){
      return (objKey[i] === key)
    }

**Comment by PashaKycher** [comment]
## Task: 153

  
  
  ## Test result 

  - [x] isKeyPresent should be exported from the file helper.js
        
  - [x] getObjectKeys should be a function
        
  - [ ] The function getObjectKeys test if the object has certain key
        
## User implementation 

  #### task153/helper.js
  ```js
  export const isKeyPresent = (obj, key) => {
  let objKey = Object.keys(obj);
    for (let i=0; i<objKey.length; i++){
      return (objKey[i] === key)
    }

}

  ```
        
  #### task153/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task153/solution.js
  ```js
  /**
 * Implement the function isKeyPresent which checks if the object has a certain field
 * */

import { isKeyPresent } from './helper.js';

const user = {
  name: 'Tom',
  age: '2',
  isHappy: true,
  createdAt: '2020-01-01'
}

console.log(isKeyPresent(user, 'name'));
console.log(isKeyPresent(user, 'address'));



  ```

**Comment by ssfxate** [comment]
You are exiting the `for` loop on the first step.
You should do `return` if it's true only.
