### ISSUE TITLE
TASK 2136 (stucked)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#83]
First of all, why do we need to name `OpenSans` instead of `Open Sans`, we've seen in Lecture 213?

## Task: 2136
```
Fonts link

There are two fonts in the fonts folder - they need to be included in the styles.css file.

The font OpenSans-Regular.ttf should be connected with a weight value of 400 and normal style
The font OpenSans-LightItalic.ttf should be connected with a weight of 300 and italic style
The first font should be used for the <div> element, the second for the paragraph.
```
  
  ## Test result 

  - [x] There should be one `<div>` element in the document.
  - [x] There should be one paragraph in the document.
  - [x] The `<div>` element's font-family should be 'OpenSans'.
  - [x] The `<div>` element's font-weight should be 400.
  - [x] The `<div>` element's font-style should be normal.
  - [x] The paragraph's font-family should be 'OpenSans'.
  - [x] The paragraph's font-weight should be 300.
  - [x] The paragraph's font-style should be italic.
  - [x] There should be two @font-face declarations for OpenSans font.
  - [ ] The @font-face rule should be used for './fonts/OpenSans-Regular.ttf' font
  - [ ] The @font-face rule should be used for './fonts/OpenSans-LightItalic.ttf' font
        
## User implementation 
```html
<!DOCTYPE>
<html>
  <head>
    <title>Website</title>
    <link rel="stylesheet" type="text/css" href="./styles.css">
    <style>
      div {
        font-family: "OpenSans", serif;
        font-weight: 400;
      }

      p {
        font-family: 'OpenSans', serif;
        font-weight: 300;
        font-style: italic;
      }
    </style>
  </head>
  <body>
    <div>Website</div>
    <p>a set of pages of information on the internet about a particular subject, published by a single person or organization.</p>
  </body>
</htmt
```

``` css
@font-face {
  font-family: 'OpenSans';
  font-weight: 400;
  font-style: normal;
	src: url('../fonts/OpenSans-Regular.ttf') format('ttf')
}

@font-face {
  font-family: 'OpenSans';
  font-weight: 300;
  font-style: italic;
  src: url('../fonts/OpenSans-LightItalic.ttf') format('ttf')
}


```

**Comment by amatiyko** [comment]
@ssfxate yes, we can think about the inconsistency between lecture and task. Naming fonts without space is better because when you apply this font, there is no need in wrapping the font with quotes.

About the two last tests: strings you provide for URLs are starting with `../`, which means that you are looking for `fonts` folder in the parent of the current directory. If you haven't added any new folders, the `fonts` folder should be in the same directory as `index.html` file. Please try change `../` to `./` - in this case you will use `fonts folder from current directiry

**Comment by ssfxate** [comment]
Solved.
